name: scenemdm
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.19
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - attrs==22.1.0
      - beautifulsoup4==4.11.1
      - blinker==1.7.0
      - blis==0.7.9
      - blobfile==2.0.0
      - catalogue==2.0.8
      - certifi==2024.2.2
      - chardet==3.0.4
      - charset-normalizer==2.1.1
      - chumpy==0.70
      - clearml==1.8.1
      - click==8.1.3
      - clip==1.0
      - colorama==0.4.6
      - comm==0.2.2
      - confection==0.0.3
      - configargparse==1.7
      - contourpy==1.0.6
      - cycler==0.11.0
      - cymem==2.0.7
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - einops==0.6.0
      - en-core-web-sm==3.4.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.8.0
      - flask==3.0.2
      - fonttools==4.38.0
      - freetype-py==2.3.0
      - fsspec==2023.4.0
      - ftfy==6.1.1
      - furl==2.1.3
      - gdown==4.6.0
      - h5py==3.8.0
      - huggingface-hub==0.11.1
      - idna==2.6
      - imageio==2.27.0
      - importlib-metadata==7.1.0
      - importlib-resources==5.10.0
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - lxml==4.9.1
      - markupsafe==2.1.1
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - more-itertools==9.0.0
      - mpmath==1.3.0
      - murmurhash==1.0.9
      - mxnet-mkl==1.5.0
      - natsort==8.4.0
      - nbformat==5.10.3
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numpy==1.23.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-htop==1.0.5
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - openmesh==1.2.1
      - openpyxl==3.1.2
      - orderedmultidict==1.0.1
      - packaging==21.3
      - pandas==1.5.2
      - parso==0.8.3
      - pathlib2==2.3.7.post1
      - pathy==0.10.0
      - pillow==9.3.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - plotly==5.11.0
      - pooch==1.8.2
      - preshed==3.0.8
      - prompt-toolkit==3.0.43
      - psutil==5.9.4
      - pure-eval==0.2.2
      - pybullet==3.2.6
      - pycryptodomex==3.16.0
      - pydantic==1.10.11
      - pyglet==1.5.29
      - pygments==2.17.2
      - pyjwt==2.4.0
      - pynavmesh==1.2.3
      - pyopengl==3.1.0
      - pyparsing==3.0.9
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyrender==0.1.45
      - pyrsistent==0.19.2
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-graphviz==0.8.4
      - pytz==2022.6
      - pyvista==0.44.1
      - pywin32==306
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.32.3
      - retrying==1.3.4
      - rtree==1.2.0
      - scikit-learn==1.4.1.post1
      - scipy==1.9.3
      - scooby==0.10.0
      - seaborn==0.13.2
      - six==1.16.0
      - smart-open==5.2.1
      - smplx==0.1.28
      - soupsieve==2.3.2.post1
      - spacy==3.4.3
      - spacy-legacy==3.0.10
      - spacy-loggers==1.0.3
      - srsly==2.4.5
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.1.0
      - termcolor==2.1.1
      - thinc==8.1.5
      - threadpoolctl==3.4.0
      - tokenizers==0.13.2
      - torch==2.2.1+cu121
      - torchaudio==2.2.1+cu121
      - torchgeometry==0.1.2
      - torchvision==0.17.1+cu121
      - tqdm==4.64.1
      - traitlets==5.14.2
      - transformers==4.25.1
      - trimesh==3.18.1
      - typer==0.7.0
      - typing-extensions==4.8.0
      - urllib3==1.22
      - vtk==9.3.1
      - wasabi==0.10.1
      - wcwidth==0.2.5
      - werkzeug==3.0.2
      - widgetsnbextension==4.0.10
      - zipp==3.11.0
